### ISSUE TITLE
Formatting Inconsistencies

### ISSUE THREAD

**Issue by avolzer** [calvin-cs262-fall2020-teamb/campusCrawl-client#35]
Elements appear at different spots depending on which phone is used. For example, 

- the progress bar doesn't reach all the way to the bottom of the screen on some devices. This is probably caused by overreliance on absolute positioning.
- a user noted that the "Let's go" button on the welcome screen showed up as inline instead of below the text
- another user didn't see the "let's go" button at all

(assigning Ridge as well as myself just because I know you're good with UI stuff. You don't have to actually work on it if you are busy with other things)

**Comment by ridgedejong** [comment]
I think everything should use relative dimensions now
