### ISSUE TITLE
Pin color/style

### ISSUE THREAD

**Issue by avolzer** [calvin-cs262-fall2020-teamb/campusCrawl-client#37]
Features that user testers think would be useful: 

- [ ] Change the color of markers for locations that have already been visited, to visualize progress along the route

- [x] Highlight the target location in some way (maybe enlarge it and show a pop-up)

- [ ] Before the tour is started, show all stops on the screen with names labeled (without having to tap each one)

Assigning all of us because I don't know who can work on it

**Comment by ridgedejong** [comment]
We did what we could in our given time period
